name: bladiway
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.1.0
  intl: ^0.19.0
  flutter_native_splash: ^2.4.5
  flutter_otp_text_field: ^1.5.1+1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  provider: ^6.1.3
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.3
  cloud_firestore: ^5.6.6
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  flutter_launcher_icons: ^0.14.3
  google_maps_flutter: ^2.5.0
  geolocator: ^13.0.4
  permission_handler: ^11.4.0
  geocoding: ^3.0.0
  google_fonts: ^6.2.1
  flutter_polyline_points: ^2.0.0
  path: ^1.8.0
  path_provider: ^2.0.11
  camera: ^0.10.0+4
  easy_localization: ^3.0.3
  flutter_custom_clippers: ^2.1.0
  cached_network_image: ^3.3.0

  

  flutter_animate: ^4.2.0  # Pour les animations fluides
  flutter_svg: ^2.0.7  # Pour les illustrations SVG
  glassmorphism: ^3.0.0
  shimmer: ^3.0.0

  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.1
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/hi.jpg
    - assets/images/Nature.png
    - assets/images/savemoney.png
    - assets/images/links.png
    - assets/images/economiser.jpg
    - assets/images/default_profile.png
    - assets/images/small_logo_without_back.png
    - assets/images/logo_without_back.png
    - assets/images/logo_with_back.png
    - assets/images/1024.png
    - assets/images/icon.png
    - assets/images/licenceVerification.jpg
    - assets/images/drivinglicence.jpg

    # Fichiers de traduction pour easy_localization
    - assets/translations/fr.json
    - assets/translations/en.json
    - assets/translations/ar.json
    - assets/translations/fr_DZ.json

flutter_icons:
  android: true
  image_path: "assets/images/logo_without_back.png"
  android_adaptive_icon_background: "#FFFFFF"
  android_adaptive_icon_foreground: "assets/images/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/images/1024.png
  image_dark: assets/images/1024.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/images/1024.png
    image_dark: assets/images/1024.png
