// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:bladiway/services/api_keys.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: ApiKeys.webApiKey,
    appId: '1:479297677978:web:26545f81fb07878db44d23',
    messagingSenderId: '479297677978',
    projectId: 'bladiway-b2d7b',
    authDomain: 'bladiway-b2d7b.firebaseapp.com',
    databaseURL: 'https://bladiway-b2d7b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bladiway-b2d7b.firebasestorage.app',
    measurementId: 'G-L16YTSHZ0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: ApiKeys.androidApiKey,
    appId: '1:479297677978:android:513a78863124d48cb44d23',
    messagingSenderId: '479297677978',
    projectId: 'bladiway-b2d7b',
    databaseURL: 'https://bladiway-b2d7b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bladiway-b2d7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: ApiKeys.iosApiKey,
    appId: '1:479297677978:ios:7e848be408f7136fb44d23',
    messagingSenderId: '479297677978',
    projectId: 'bladiway-b2d7b',
    databaseURL: 'https://bladiway-b2d7b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bladiway-b2d7b.firebasestorage.app',
    iosBundleId: 'com.example.bladiway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: ApiKeys.macosApiKey,
    appId: '1:479297677978:ios:7e848be408f7136fb44d23',
    messagingSenderId: '479297677978',
    projectId: 'bladiway-b2d7b',
    databaseURL: 'https://bladiway-b2d7b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bladiway-b2d7b.firebasestorage.app',
    iosBundleId: 'com.example.bladiway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: ApiKeys.windowsApiKey,
    appId: '1:479297677978:web:861e5873d37be972b44d23',
    messagingSenderId: '479297677978',
    projectId: 'bladiway-b2d7b',
    authDomain: 'bladiway-b2d7b.firebaseapp.com',
    databaseURL: 'https://bladiway-b2d7b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bladiway-b2d7b.firebasestorage.app',
    measurementId: 'G-F94RH48S96',
  );

}